apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRuleObject
metadata:
  creationTimestamp: null
  labels:
    rule: volume-resize
  name: pvc-ddfb4003-0a90-425b-a232-debf61299be0
  ownerReferences:
  - apiVersion: autopilot.libopenstorage.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AutopilotRule
    name: volume-resize
    uid: 498036b9-bd06-42cd-9e23-7bc51f4d9e93
  uid: 93d3424e-6dee-459c-a91e-b194e9d8771a
spec:
  actionApprovals:
  - action:
      expectedResult: PVC will resize from 40Gi to 80Gi
      name: openstorage.io.action.volume/resize
      objectMetadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"pgbench-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"postgres-pgbench-sc"}}
          rule: volume-resize
          ruleobject: pvc-ddfb4003-0a90-425b-a232-debf61299be0
          volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
          volume.kubernetes.io/storage-resizer: kubernetes.io/portworx-volume
        creationTimestamp: null
        labels:
          app: postgres
        name: pgbench-data
        namespace: default
        ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: pgbench-5f84f5b884
          uid: 3018edf8-efb3-40c5-b77c-6e5dfc76f055
        selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pgbench-data
        type: PersistentVolumeClaim
        uid: ddfb4003-0a90-425b-a232-debf61299be0
      params:
        scalepercentage: "100"
    state: approved
status: {}
