apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRuleObject
metadata:
  creationTimestamp: "2020-04-10T23:46:59Z"
  generation: 2
  labels:
    rule: volume-resize
  name: pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
  ownerReferences:
  - apiVersion: autopilot.libopenstorage.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AutopilotRule
    name: volume-resize
    uid: 9c84579c-5e5c-47fa-8a7d-1c9a89ee8fc1
  resourceVersion: "2393894"
  selfLink: /apis/autopilot.libopenstorage.org/v1alpha1/autopilotruleobjects/pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
  uid: ca7b2289-7f7c-4ae9-be50-1eba5a51dd19
spec:
  actionApprovals:
  - action:
      expectedResult: PVC will resize from 20Gi to 40Gi
      name: openstorage.io.action.volume/resize
      objectMetadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"pgbench-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"postgres-pgbench-sc"}}
          rule: volume-resize
          ruleobject: pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
          volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
          volume.kubernetes.io/storage-resizer: kubernetes.io/portworx-volume
        creationTimestamp: null
        labels:
          app: postgres
        name: pgbench-data
        namespace: default
        ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: pgbench-5f84f5b884
          uid: 3ea649f3-61ac-4f21-a60b-7ed033509f2b
        selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pgbench-data
        uid: d94b06a1-c88c-42d4-a494-99f1c43c0915
      params:
        scalepercentage: "100"
    state: approved
status:
  items:
  - lastProcessTimestamp: "2020-04-10T23:46:59Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from Normal => Triggered'
    state: Triggered
  - lastProcessTimestamp: "2020-04-10T23:47:12Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from Triggered => ActionAwaitingApproval'
    state: ActionAwaitingApproval
