apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRuleObject
metadata:
  creationTimestamp: null
  labels:
    rule: volume-resize
  name: pvc-5ddfc552-fe82-46e5-8eb6-c752c9cee399
  ownerReferences:
  - apiVersion: autopilot.libopenstorage.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AutopilotRule
    name: volume-resize
    uid: 498036b9-bd06-42cd-9e23-7bc51f4d9e93
  uid: 4d5c2fdd-afbb-402e-a490-1d01d226a608
spec:
  actionApprovals:
  - action:
      expectedResult: PVC will resize from 3Gi to 6Gi
      name: openstorage.io.action.volume/resize
      objectMetadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"pgbench-data","namespace":"pg3"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}},"storageClassName":"postgres-pgbench-sc"}}
          rule: volume-resize
          ruleobject: pvc-5ddfc552-fe82-46e5-8eb6-c752c9cee399
          volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
        creationTimestamp: null
        labels:
          app: postgres
        name: pgbench-data
        namespace: pg3
        selfLink: /api/v1/namespaces/pg3/persistentvolumeclaims/pgbench-data
        type: PersistentVolumeClaim
        uid: 5ddfc552-fe82-46e5-8eb6-c752c9cee399
      params:
        scalepercentage: "100"
    state: approved
status: {}
