apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRuleObject
metadata:
  annotations:
    fluxcd.io/sync-checksum: c090e7014c61482e75f4249a0fa62e36a28ebf87
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autopilot.libopenstorage.org/v1alpha1","kind":"AutopilotRuleObject","metadata":{"annotations":{"fluxcd.io/sync-checksum":"c090e7014c61482e75f4249a0fa62e36a28ebf87"},"creationTimestamp":"2020-04-10T22:08:33Z","generation":2,"labels":{"fluxcd.io/sync-gc-mark":"sha256.f4y8vMFDHamsoMwLfPL0BX1UkdMZ-hX928qLfYxxYw0","rule":"volume-resize"},"name":"pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915","ownerReferences":[{"apiVersion":"autopilot.libopenstorage.org/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"AutopilotRule","name":"volume-resize","uid":"35b37e2c-a76f-470f-8f41-b7830fa4d9b4"}],"resourceVersion":"2375719","selfLink":"/apis/autopilot.libopenstorage.org/v1alpha1/autopilotruleobjects/pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915","uid":"8643356d-6f6f-4a32-8dc7-beb96c461640"},"spec":{"actionApprovals":[{"action":{"expectedResult":"PVC will resize from 10Gi to 20Gi","name":"openstorage.io.action.volume/resize","objectMetadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"postgres\"},\"name\":\"pgbench-data\",\"namespace\":\"default\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"storageClassName\":\"postgres-pgbench-sc\"}}\n","rule":"volume-resize","ruleobject":"pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915","volume.beta.kubernetes.io/storage-provisioner":"kubernetes.io/portworx-volume"},"creationTimestamp":null,"labels":{"app":"postgres"},"name":"pgbench-data","namespace":"default","ownerReferences":[{"apiVersion":"apps/v1","blockOwnerDeletion":true,"controller":true,"kind":"ReplicaSet","name":"pgbench-5f84f5b884","uid":"3ea649f3-61ac-4f21-a60b-7ed033509f2b"}],"selfLink":"/api/v1/namespaces/default/persistentvolumeclaims/pgbench-data","uid":"d94b06a1-c88c-42d4-a494-99f1c43c0915"},"params":{"scalepercentage":"100"}},"state":"approved"}]},"status":{"items":[{"lastProcessTimestamp":"2020-04-10T22:08:33Z","message":"rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition from Normal =\u003e Triggered","state":"Triggered"},{"lastProcessTimestamp":"2020-04-10T22:08:47Z","message":"rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition from Triggered =\u003e ActionAwaitingApproval","state":"ActionAwaitingApproval"}]}}
  creationTimestamp: "2020-04-10T22:08:33Z"
  generation: 8
  labels:
    fluxcd.io/sync-gc-mark: sha256.f4y8vMFDHamsoMwLfPL0BX1UkdMZ-hX928qLfYxxYw0
    rule: volume-resize
  name: pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
  ownerReferences:
  - apiVersion: autopilot.libopenstorage.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AutopilotRule
    name: volume-resize
    uid: 35b37e2c-a76f-470f-8f41-b7830fa4d9b4
  resourceVersion: "2377958"
  selfLink: /apis/autopilot.libopenstorage.org/v1alpha1/autopilotruleobjects/pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
  uid: 8643356d-6f6f-4a32-8dc7-beb96c461640
spec:
  actionApprovals:
  - action:
      expectedResult: PVC will resize from 10Gi to 20Gi
      name: openstorage.io.action.volume/resize
      objectMetadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"pgbench-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"postgres-pgbench-sc"}}
          rule: volume-resize
          ruleobject: pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915
          volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
        creationTimestamp: null
        labels:
          app: postgres
        name: pgbench-data
        namespace: default
        ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: pgbench-5f84f5b884
          uid: 3ea649f3-61ac-4f21-a60b-7ed033509f2b
        selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pgbench-data
        uid: d94b06a1-c88c-42d4-a494-99f1c43c0915
      params:
        scalepercentage: "100"
    state: approved
status:
  items:
  - lastProcessTimestamp: "2020-04-10T22:08:33Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from Normal => Triggered'
    state: Triggered
  - lastProcessTimestamp: "2020-04-10T22:08:47Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from Triggered => ActionAwaitingApproval'
    state: ActionAwaitingApproval
  - lastProcessTimestamp: "2020-04-10T22:11:13Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from ActionAwaitingApproval => ActiveActionsPending'
    state: ActiveActionsPending
  - lastProcessTimestamp: "2020-04-10T22:11:13Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from ActiveActionsPending => ActiveActionsInProgress'
    state: ActiveActionsInProgress
  - lastProcessTimestamp: "2020-04-10T22:11:13Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from ActiveActionsInProgress => ActiveActionsTaken'
    state: ActiveActionsTaken
  - lastProcessTimestamp: "2020-04-10T22:20:35Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from ActiveActionsTaken => Triggered'
    state: Triggered
  - lastProcessTimestamp: "2020-04-10T22:20:49Z"
    message: 'rule: volume-resize:pvc-d94b06a1-c88c-42d4-a494-99f1c43c0915 transition
      from Triggered => ActionAwaitingApproval'
    state: ActionAwaitingApproval
