apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: ActionApproval
metadata:
  creationTimestamp: null
  labels:
    object: pvc-ec475444-e2d6-4533-863b-03263da7b04c
    rule: volume-resize
  name: volume-resize-pvc-ec475444-e2d6-4533-863b-03263da7b04c
  namespace: pg1
spec:
  actions:
  - name: resize
    params:
      maxsize: 400Gi
      scalepercentage: "100"
  approvalState: approved
status:
  Rule:
    Name: volume-resize
    Namespace: ""
  actionPreviews:
  - action:
      name: resize
      params:
        maxsize: 400Gi
        scalepercentage: "100"
    expectedResult:
      Message: PVC will resize from 10Gi to 20Gi
    involvedObjects:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: pgbench-data
      namespace: pg1
      ownerReferences:
      - apiVersion: apps/v1
        blockOwnerDeletion: true
        controller: true
        kind: ReplicaSet
        name: pgbench-7f64fc8444
        uid: 2ac06424-f802-4d53-8342-e302846aceef
      uid: pvc-ec475444-e2d6-4533-863b-03263da7b04c
  lastProcessTimestamp: "2020-08-25T23:20:18Z"
